language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - python3 backend/src/mortgagecalculator/manage.py runserver & python3 test/tests.py &