# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='dummy',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
