# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-19 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20180719_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housepicture',
            name='houseFkey',
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='picURL',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HousePicture',
        ),
    ]
