# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-12 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_houseinfo_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseinfo',
            name='dummy',
        ),
    ]
