# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-17 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_houseinfo_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
