# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-20 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20180719_1620'),
        ('apis', '0003_auto_20180719_1907'),
    ]

    operations = [
    ]
