# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-18 13:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_houseinfo_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='realtorFname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='realtorLname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
