# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-18 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20180718_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseinfo',
            name='realtorEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
